### PR TITLE
fix: og image cards overflow

### LINKED ISSUE #88: OG Image wrong colors and cards are overflowing
Hello! I noticed that the Nuxters OG image has wrong colors making the rank not visible, and the cards are overflowing, I marked the problems in the image below, you can check it in the following link https://nuxters.nuxt.com/card/Yizack/og.png

image

I believe the card should look somewhat like the card in this [X post from Atinux](https://x.com/Atinux/status/1764964513231614275) months ago

I'm opening a PR to help fix the issue :)

### PR DESCRIPTION
**Pull request by Yizack**
### 🔗 Linked issue

resolves #88 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

~~I'm not a Tailwind expert but it seems like the og module is not seeing the colors when using classes like `bg-gray-900`, `text-gray-400` so instead I used [Arbitrary values](https://tailwindcss.com/docs/text-color#arbitrary-values). If someone knows how to make the color classes work the help is welcomed!~~

And for fixing the overflowing I simply added the `overflow-hidden` tailwing class to each card

The image below is how it looks with the changes

image

### CODE REVIEW

File: components/OgImage/OgImageNuxter.vue [hunk 1]
```diff
@@ -40,7 +40,7 @@ const format = useNumberFormatter()
           </svg>
           <div class="font-medium text-4xl pl-2 pt-1">{{ format(contributor.score) }}</div>
         </div>
-        <div class="flex flex-row text-gray-400 items-center pt-3 font-medium text-3xl">
+        <div class="flex flex-row text-[#94a3b8] items-center pt-3 font-medium text-3xl">
```
Comment (arashsheyda) [inline components/OgImage/OgImageNuxter.vue:43]: what's the reason for not using tailwind colours?

File: components/OgImage/OgImageNuxter.vue [hunk 2]
```diff
@@ -10,7 +10,7 @@ const format = useNumberFormatter()
 </script>
 
 <template>
-  <div class="flex flex-row justify-between w-full p-[38px] bg-gray-900">
+  <div class="flex flex-row justify-between w-full p-[38px] bg-[#0f172a]">
```
Comment (arashsheyda) [inline components/OgImage/OgImageNuxter.vue:13]: can you add `h-full` so we get rid of the white space at the bottom? thanks

File: components/OgImage/OgImageNuxter.vue (hunk 1 above)
Comment (Yizack) [reply components/OgImage/OgImageNuxter.vue]: Alright, I updated my branch from upstream and it seems like the tailwind colors issue has been resolved with some dependency updates so I reverted back the classes from my PR

**Review by arashsheyda — APPROVED** [review]
looks great! thank you for fixing this
